homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  whitelist_external_dirs: 
  - /tmp
  - /home/pi/.homeassistant/downloads
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

sun:
frontend:
 javascript_version: es5
config:
ios:
updater:
 include_used_components: true
discovery:
conversation:
history:
  exclude:
    domains:
      - automation
logbook:
  exclude:
    domains:
      - automation
recorder:
  purge_interval: 2
  purge_keep_days: 8
  exclude:
    domains:
      - automation
map:
tts:
  - platform: google

influxdb:
  host: 127.0.0.1
  include:
   entities:
   - sensor.energy_generation
   - sensor.power_generation
   - sensor.iphone_van_martin_battery_level
   - sensor.roomba_battery
   - sensor.power_consumption_low
   - sensor.power_consumption_normal
   - sensor.power_production_low
   - sensor.power_production_normal
   - sensor.gas_consumption
#  exclude:
#   entities:
#   - sensor.pvoutput
#   - sensor.serial_sensor
#   - sensor.yr_symbol

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id1

downloader:
  download_dir: downloads
python_script:
automation: !include automations.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
history_graph: !include history_graph.yaml
light: !include light.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
script: !include_dir_merge_named scripts
sensor: !include sensors.yaml
switch: !include switch.yaml
