homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  whitelist_external_dirs: 
  - /tmp
  - /home/pi/.homeassistant/downloads
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key

sun:
frontend:
 javascript_version: es5
config:
updater:
 include_used_components: true
discovery:
conversation:
map:
tts:
  - platform: google
    language: 'nl'

zwave:
  usb_path: /dev/ttyACM1

mqtt:
 broker: 127.0.0.1
 client_id: homeassistant
 username: !secret mqtt_username
 password: !secret mqtt_password
 keepalive: 60
 protocol: 3.1
 birth_message:
   topic: "tele/homeassistant/LWT"
   payload: "Online"
   qos: 1
   retain: true
 will_message:
   topic: "tele/homeassistant/LWT"
   payload: "Offline"
   qos: 1
   retain: true

climate:
  - platform: homewizard
    name: Heatlink
    host: !secret homewizard_ip
    password: !secret homewizard_password
    # not sure if this works:
    scan_interval: 10

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_chat_id1

panel_iframe:
 pvoutput:
  title: 'PVOutput'
  icon: mdi:chart-line
  url: !secret pvoutput_url

xiaomi_aqara:
  discovery_retry: 5
  gateways:
    key: !secret xiaomi_gateway_key

downloader:
  download_dir: downloads
python_script: !include_dir_merge_named python_scripts
automation: !include_dir_merge_list automations
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
device_tracker: !include device_tracker.yaml
group: !include groups.yaml
history: !include history.yaml
history_graph: !include history_graph.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
ios: !include ios.yaml
light: !include light.yaml
logbook: !include logbook.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
recorder: !include recorder.yaml
script: !include_dir_merge_named scripts
sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
switch: !include switch.yaml
zone: !include zone.yaml
