- platform: vlc
  name: speaker_1
  arguments: '--alsa-audio-device=hw:0,0'
- platform: samsungtv
  host: 172.19.3.12
  port: 8001
  name: TV
  mac: D8:E0:E1:01:0C:FF
- platform: denonavr
  host: 172.19.3.13
  name: Denon Receiver
  show_all_sources: False
  timeout: 2
- platform: ziggo_mediabox_xl
  host: 172.19.3.24
  name: Ziggo Mediabox
- platform: spotify
  client_id: 9d9c685427e14c7fb0528b8085ceaaca
  client_secret: 1059bc26ced84d9bab9cc5361f977572