- alias: 'Light turn off Voordeurlamp at sunrise' 
  trigger:
    platform: sun
    event: sunrise
    offset: "-00:30:00"
  action:
    service: homeassistant.turn_off
    entity_id: switch.plug_158d0001a4ea40