- alias: Notify door opened not home
  trigger:
    platform: state
    entity_id: 
     - binary_sensor.door_window_sensor_158d0001a1ecd5  #voordeur
     - binary_sensor.door_window_sensor_158d0001dbcc33  #achterdeur
     # voeg evt meer toe
    from: 'off'
    to: 'on'
#    for:          # avoid double notifications
#     seconds: 1
  condition: 
   condition: and 
   conditions: 
    - condition: state 
      entity_id: 'device_tracker.iphonevanmartin' 
      state: 'not_home' 
    - condition: state 
      entity_id: 'device_tracker.iphonevanilse' 
      state: 'not_home' 
  action:
    - service: notify.martinenilse
      data_template:
        title: '{{ trigger.to_state.attributes.friendly_name }} geopend!'
        message: >
                 De {{ trigger.to_state.attributes.friendly_name }} is geopend!
      data:
       data:
        push:
         sound: US-EN-Morgan-Freeman-Front-Door-Opened.wav
