# Notificatie Martin van Werk naar Huis
- alias: Notify Travel Martin werk naar huis
  trigger:
    platform: state
    entity_id: device_tracker.iphone_van_martin
    from: 'Work'
    to: 'not_home'
  condition:
    - condition: time
      after: '17:00:00'
      before: '17:45:00'
  action:
    - service: notify.martinenilse
      data_template:
        title: "Martin gaat van werk naar huis!"
        message: >
          Hij komt om ongeveer {{ ( as_timestamp(now()) + (states("sensor.travel_time_martin_to_home") | int)  * 60 )  | timestamp_custom("%H:%M") }} aan.
