# Notificatie Martin van Werk naar Huis
- alias: Notify Travel Martin werk naar huis
  trigger:
    platform: state
    entity_id: device_tracker.iphone_van_martin
    from: 'work'
    to: 'not_home'
  condition:
    - condition: time
      after: '17:00:00'
      before: '17:45:00'
  action:
    service: notify.ios_iphone_van_martin
    data_template:
      title: "Martin gaat van werken naar huis!"
      message: >
        en komt aan om {{ ( as_timestamp(now()) + (states("sensor.travel_time_martin_to_home") | int)  * 60 )  | timestamp_custom("%H:%M") }}.
