- alias: Notify door opened
  trigger:
    platform: state
    entity_id: 
     - binary_sensor.door_window_sensor_158d0001a1ecd5  #voordeur
     # voeg evt meer toe
    from: 'off'
    to: 'on'
    for:          # avoid double notifications
     seconds: 1
  action:
    - service: notify.ios_iphone_van_martin
      data_template:
        title: '{{ trigger.to_state.attributes.friendly_name }} geopend!'
        message: >
                 De {{ trigger.to_state.attributes.friendly_name }} is geopend!
      data:
       data:
        push:
         sound: US-EN-Morgan-Freeman-Front-Door-Opened.wav
