- alias: Notify Doorbell
  trigger:
    platform: state
    entity_id: 
     - binary_sensor.doorbell  #deurbel
    from: 'off'
    to: 'on'
#  condition:
#    condition: template
#    value_template: '{{ (as_timestamp(now()) - as_timestamp(states.automation.automation_notify_doorbell.attributes.last_triggered | default(0)) | int > 10)}}'
  action:
    - service: camera.snapshot
      data:
       entity_id: camera.voordeur
       filename: '/home/pi/.homeassistant/downloads/camera_snapshots/voordeurcam.jpg'
    - service: notify.martinenilse
      data:
       message: 'Deurbel: Er is aangebeld!'
       data:
           attachment: 
             url: !secret foscam_snapshot_url
             content-type: jpeg
