- alias: Switch Keuken
  initial_state: on
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_158d00015f24d1
        click_type: single
  action:
    - service: switch.toggle
      entity_id: switch.plug_158d0001a6592f